name: Run Oracle Database

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run Oracle Database
        run: |
          docker run -d --name oracle-db \
          -e ORACLE_PWD=YourPassword \
          -p 1521:1521 \
          oracle/database:latest
