name: Oracle DB Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start Oracle DB Container
      run: |
        docker run -d --name vendb \
          -e ORACLE_RANDOM_PASSWORD=sys_user_password \
          -e APP_USER=my_user \
          -e APP_USER_PASSWORD=password_i_should_change \
          -p 1521:1521 \
          gvenzl/oracle-free:latest

    - name: Wait for Oracle DB to be Ready
      run: |
        # Wait for the database to be fully initialized
        sleep 35

    - name: Run SQL Command on Oracle DB
      run: |
        # Execute SQL command inside the container
         docker exec vendb bash -c "echo 'SELECT * FROM dual;' | sqlplus -S / as sysdba"
