name: Oracle DB Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      oracle:
        image: gvenzl/oracle-free:latest
        options: --publish 1521:1521  # Expose Oracle DB port

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Oracle DB and run commands
      run: |
        # Wait for the database to be ready
        sleep 30  # Adjust as needed to allow DB startup time
        # Example: Run SQL command inside the container
        docker exec -it vendb bash -c "echo 'SELECT * FROM dual;' | sqlplus -S / as sysdba"
